@url = http://localhost:8080/api/movie
@movieID = 1

GET {{url}} HTTP/1.1

###

GET {{url}}/{{movieID}} HTTP/1.1

###

GET {{url}}/{{movieID}}/director

###

GET {{url}}/{{movieID}}/writer

###

GET {{url}}/{{movieID}}/star